name: GraalVM build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_PASSWORD: admin_pass
          POSTGRES_USER: admin
          POSTGRES_DB: smartscrumpoker
        ports:
          - 5432:5432
    permissions: # The permissions the surefire test report
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo "COMMIT_SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Example step
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Hosts file update "localhost.balazskrizsan.com" -> 127.0.0.1
        run: |
          sudo echo "127.0.0.1 	localhost.balazskrizsan.com" | sudo tee -a /etc/hosts

      - name: Build
        env:
          SERVER_ENV: DEV
          SERVER_PORT: 9999
          SERVER_SOCKET_FULL_HOST: wss://localhost.balazskrizsan.com:9999/ws
          SERVER_SSL_ENABLED: true
          SERVER_SSL_KEY_STORE: classpath:keystore/dev.p12
          SERVER_SSL_KEY_STORE_PASSWORD: password
          SITE_DOMAIN: not.yet
          SITE_FRONTEND_HOST: https://localhost:4200
          SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 10
          SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 10
          SPRING_DATASOURCE_PASSWORD: admin_pass
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/smartscrumpoker
          SPRING_DATASOURCE_USERNAME: admin
          SOCKET_IS_ENABLED_SOCKET_CONNECT_AND_DISCONNECT_LISTENERS: false
          NATIVE_REFLECTION_CONFIGURATION_GENERATOR_ENABLED: false
          SOCKET_MESSAGE_BROKER_STATS_LOGGING_PERIOD_SECONDS: 6000
        run: mvn native:compile -Pnative -Dspring.profiles.active=native

      - uses: scacap/action-surefire-report@v1
        if: success() || failure()
        # if: github.ref != 'refs/heads/master'
        with:
          check_name: Surefire test report
          report_paths: '**/surefire-reports/*.xml'

      - name: File system info
        run: |
          echo "===========> github.workspace var: ${{ github.workspace }}"
          echo "===========> pwd:"
          pwd
          echo "===========> ls -hal:"
          ls -hal
          echo "===========> ls -hal /src:"
          ls -hal ./src
          echo "===========> ls -hal /target:"
          ls -hal ./target

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: kbalazsworks/smart_scrum_poker_backend_native:${{ env.RELEASE_VERSION }}, kbalazsworks/smart_scrum_poker_backend_native:latest, kbalazsworks/smart_scrum_poker_backend_native:commit_sha_short_${{ env.COMMIT_SHA_SHORT }}
